### ISSUE TITLE
An example to use LM optimizer

### ISSUE THREAD

**Issue by sashahexe** [hahnec/torchimize#2]
Hi, 

thank you for your library, I'd like to use the LM optimizer in my PINN which is set up as a class based on pytorch. Could you share some examples of the code where you use the LM as an optimizer? 

Thanks again!

**Comment by AtaraxiaZ** [comment]
Hi,

I also want to use LM optimizer, but I don't know the relationship between lma_fun_single and a LM optimizer. Could you give an example on how to use lma_fun_single on a simple fully-connected neural network?
